all: stat
stat: stat.cpp
	g++ -std=c++11 -o stat stat.cpp
server: server.cpp
	g++ -std=c++11 -o server server.cpp
exserv2: exampleServer2.cpp
	g++ -std=c++11 -o exserv2 exampleServer2.cpp
sigint: sigint.cpp
	g++ -std=c++11 -o sigint sigint.cpp
cleanstat: 
	rm stat
cleanserver:
	rm server
cleanexserv2:
	rm exserv2
cleansigint:
	rm sigint
cleanall:
	rm stat
	rm server
	rm exserv2
	rm sigint